//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhThawngs_10119056_DoAn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDonHang
    {
        public int MaCT { get; set; }
        public string MaDH { get; set; }
        public Nullable<int> MaLK { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual LinhKien LinhKien { get; set; }
    }
}
