//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhThawngs_10119056_DoAn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiLinhKien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiLinhKien()
        {
            this.LinhKien = new HashSet<LinhKien>();
        }
    
        public int MaLoaiLK { get; set; }
        public Nullable<int> MaLoaiLKCha { get; set; }
        public string TenLoaiLK { get; set; }
        public string Anh { get; set; }
        public string MaMenu { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinhKien> LinhKien { get; set; }
    }
}
