//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhThawngs_10119056_DoAn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int MaTT { get; set; }
        public string TieuDe { get; set; }
        public System.DateTime NgayDang { get; set; }
        public string Anh { get; set; }
        public int MaLoaiTT { get; set; }
        public string NoiDung { get; set; }
    
        public virtual LoaiTinTuc LoaiTinTuc { get; set; }
    }
}
